const ALLOWED_SPORTS = new Set([
  'soccer','basketball','tennis','table-tennis','cricket','american-football','australian-rules','badminton','baseball','darts','esports','ice-hockey','martial-arts','rugby','volleyball'
]);
function clamp(value,min,max,fallback){const n=Number(value);if(!Number.isFinite(n))return fallback;return Math.max(min,Math.min(max,Math.floor(n)));}
function sleep(ms){return new Promise(r=>setTimeout(r,ms));}
function isVirtualEsport(event){const text=[event?.moreInfo?.esport,event?.league,event?.home,event?.away,event?.name,event?.tournament].filter(Boolean).join(' ').toLowerCase();return text.includes('esoccer')||text.includes('ebasketball')||text.includes('esim')||text.includes('virtual')||text.includes('simulated')||text.includes('simulation')||text.includes('madden nfl');}
function getEventId(event,index,page){return String(event?.eventId??event?.id??event?._id??`${page}-${index}-${event?.home||''}-${event?.away||''}-${event?.startTime||''}`);}
function compactEvent(event){return{eventId:event?.eventId??event?.id??event?._id??null,startTime:event?.startTime??event?.start??event?.date??null,status:event?.status??event?.state??null,live:event?.live??event?.isLive??null,league:event?.league??event?.tournament??event?.competition??null,home:event?.home??event?.homeTeam??event?.participant1??null,away:event?.away??event?.awayTeam??event?.participant2??null,moreInfo:event?.moreInfo??null,markets:event?.markets??event?.odds??event?.betOffers??null};}
async function fetchPulsePage({apiKey,sport,mode,eventId,page,limit}){let p;if(eventId&&mode==='live')p=`/live-events/events/${encodeURIComponent(eventId)}`;else if(eventId)p=`/${encodeURIComponent(sport)}/events/${encodeURIComponent(eventId)}`;else if(mode==='live')p=`/live-events?sport=${encodeURIComponent(sport)}&page=${page}&limit=${limit}`;else p=`/${encodeURIComponent(sport)}/events?page=${page}&limit=${limit}`;const upstream=await fetch(`https://api.pulsescore.net/api/thunderpick${p}`,{headers:{'X-Secret':apiKey,'Accept-Encoding':'gzip',Accept:'application/json'}});const raw=await upstream.text();let data;try{data=JSON.parse(raw);}catch{const e=new Error('PulseScore returned non-JSON');e.status=502;throw e;}return{ok:upstream.ok,status:upstream.status,data};}
export default async function handler(req,res){
 if(req.method==='OPTIONS'){res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','GET, OPTIONS');return res.status(204).end();}
 if(req.method!=='GET')return res.status(405).json({error:'GET only'});
 const apiKey=process.env.PULSESCORE_API_KEY||process.env.PULSESCORE_KEY||process.env.PULSE_API_KEY;if(!apiKey)return res.status(500).json({error:'PulseScore API key is not configured on Vercel'});
 const sport=String(req.query.sport||'').toLowerCase();if(!ALLOWED_SPORTS.has(sport))return res.status(400).json({error:'Unsupported sport',allowedSports:[...ALLOWED_SPORTS]});
 const mode=String(req.query.mode||'upcoming').toLowerCase(),eventId=req.query.eventId?String(req.query.eventId):null,page=clamp(req.query.page,1,1000,1),limit=clamp(req.query.limit,1,30,30),realOnly=String(req.query.realOnly||'0')==='1',scanAll=String(req.query.scanAll||'0')==='1',startPage=clamp(req.query.startPage,1,1000,1),maxPages=clamp(req.query.maxPages,1,20,4);
 res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Cache-Control','no-store');
 try{
  if(!scanAll||eventId){const result=await fetchPulsePage({apiKey,sport,mode,eventId,page,limit});if(!result.ok)return res.status(result.status).json({error:'PulseScore request failed',upstreamStatus:result.status,upstream:result.data});const data=result.data;let virtualExcluded=0;const rawEventCount=Array.isArray(data.events)?data.events.length:eventId?1:0;if(sport==='esports'&&realOnly&&Array.isArray(data.events)){data.events=data.events.filter(e=>{const v=isVirtualEsport(e);if(v)virtualExcluded++;return !v;});}return res.status(200).json({...data,proxyFetchedAt:new Date().toISOString(),source:'LIVE THUNDERPICK FEED via PulseScore',rawEventCount,virtualExcluded,returnedEventCount:Array.isArray(data.events)?data.events.length:rawEventCount});}
  const uniqueEvents=new Map();let totalRaw=0,virtualExcluded=0,pagesFetched=0,terminalReason='batch limit reached',rateLimited=false,previousIds=null;const endPage=startPage+maxPages-1;
  for(let currentPage=startPage;currentPage<=endPage;currentPage++){if(currentPage>startPage)await sleep(1500);let result=await fetchPulsePage({apiKey,sport,mode,eventId:null,page:currentPage,limit});if(result.status===429){await sleep(5000);result=await fetchPulsePage({apiKey,sport,mode,eventId:null,page:currentPage,limit});}if(result.status===429){rateLimited=true;terminalReason=`429 rate limit before page ${currentPage}`;break;}if(!result.ok){terminalReason=`upstream error ${result.status} on page ${currentPage}`;break;}pagesFetched++;const events=Array.isArray(result.data?.events)?result.data.events:[];totalRaw+=events.length;if(!events.length){terminalReason=`empty page ${currentPage}`;break;}const ids=events.map((e,i)=>getEventId(e,i,currentPage));if(previousIds&&ids.length===previousIds.length&&ids.every((id,i)=>id===previousIds[i])){terminalReason=`page ${currentPage} repeated previous page`;break;}previousIds=ids;for(let i=0;i<events.length;i++){const e=events[i];if(sport==='esports'&&realOnly&&isVirtualEsport(e)){virtualExcluded++;continue;}const id=getEventId(e,i,currentPage);if(!uniqueEvents.has(id))uniqueEvents.set(id,compactEvent(e));}if(events.length<limit){terminalReason=`short final page ${currentPage}: ${events.length}/${limit}`;break;}}
  const events=[...uniqueEvents.values()];return res.status(200).json({source:'LIVE THUNDERPICK FEED via PulseScore',proxyFetchedAt:new Date().toISOString(),sport,mode,startPage,pagesFetched,nextPage:startPage+pagesFetched,rawEventCount:totalRaw,virtualExcluded,returnedEventCount:events.length,terminalReason,rateLimited,events});
 }catch(error){return res.status(error?.status||502).json({error:'Proxy request failed',message:error?.message||'Unknown error'});}
}
